version: "3"

networks:
  eshop_network:
    external: true

services:
  eshop_nginx:
    image: nginx:1.19.1
    container_name: eshop_nginx
    ports:
      - "8095:80"
    restart: always
    networks:
      - eshop_network
    depends_on:
      - eshop_laravel
    links:
      - eshop_laravel
    volumes:
      - ./docker/nginx/eshop_laravel.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
      - ./docker/logs/nginx:/var/logs/nginx

  eshop_laravel: &laravel-template
    image: eshop_laravel:latest
    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=dev"
        - "BUILD_ARGUMENT_DEBUG_ENABLED=false"
      dockerfile: ./Dockerfile
    container_name: eshop_laravel
    restart: always
    networks:
      - eshop_network
    expose:
      - 9000
    links:
      - eshop_redis
      - eshop_mysql
    depends_on:
      - eshop_redis
      - eshop_mysql
    volumes:
      - ./:/var/www/html

  eshop_redis:
    image: redis:6.0.6
    container_name: eshop_redis
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - eshop_network

  eshop_mysql:
    image: mysql:8.0.21
    container_name: eshop_mysql
    restart: always
    networks:
      - eshop_network
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/databases:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'eshop'
      MYSQL_USER: 'eshop'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'      
#     environment:
#       MYSQL_ROOT_PASSWORD: 123456789
#       MYSQL_DATABASE: '${DB_DATABASE}'
#       MYSQL_USER: '${DB_USERNAME}'
#       MYSQL_PASSWORD: '${DB_PASSWORD}'
